# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wWQQq-mGwi8s5ozq2lbjLVq2NOtOO4A5

#Common functions
"""